import dataikuapi
import os
from dotenv import load_dotenv

load_dotenv()

DSS_URL = os.environ["DSS_URL"]
API_KEY = os.environ["DSS_API_KEY"]
PROJECT_KEY = "ANALYTICAL_READY_DATASETS"

client = dataikuapi.DSSClient(DSS_URL, API_KEY)
project = client.get_project(PROJECT_KEY)

wiki = project.get_wiki()

ARTICLE_BODY = r"""
# Analytical Ready Datasets - Flow Documentation
**Project Key:** ANALYTICAL_READY_DATASETS
**Generated:** 2026-10-03 (auto-generated by Cortex Code)

---

## Flow Diagram

```
PATIENTS (source)              PRESCRIPTIONS (source)
    |                               |
    +-------> join_patients_prescriptions (LEFT JOIN on PATIENT_ID)
                        |
              PATIENTS_PRESCRIPTIONS_joined
                        |
                        +-------> join_with_doctors (LEFT JOIN on DOCTOR_ID)
                        |                |
              DOCTORS (source)   PATIENT_DOCTOR_RX
                                         |
                                  group_rx_by_drug (GROUP BY DRUG_NAME, SPECIALTY)
                                         |
                                  RX_BY_DRUG_SUMMARY (final output)
```

---

## Source Datasets

### PATIENTS
- **Type:** UploadedFiles
- **Rows:** 12
- **Columns:**

| Column | Type |
|--------|------|
| PATIENT_ID | string |
| NAME | string |
| AGE | string |
| GENDER | string |
| DIAGNOSIS | string |
| ADMISSION_DATE | string |
| DOCTOR_ID | string |

### PRESCRIPTIONS
- **Type:** UploadedFiles
- **Rows:** 18
- **Columns:**

| Column | Type |
|--------|------|
| RX_ID | string |
| PATIENT_ID | string |
| DRUG_NAME | string |
| DOSAGE | string |
| FREQUENCY | string |
| START_DATE | string |
| END_DATE | string |
| PRESCRIBING_DOCTOR_ID | string |

### DOCTORS
- **Type:** UploadedFiles
- **Rows:** 5
- **Columns:**

| Column | Type |
|--------|------|
| DOCTOR_ID | string |
| NAME | string |
| SPECIALTY | string |
| DEPARTMENT | string |
| LICENSE_NUMBER | string |

---

## Recipes

### 1. join_patients_prescriptions (Join)
- **Inputs:** PATIENTS, PRESCRIPTIONS
- **Output:** PATIENTS_PRESCRIPTIONS_joined
- **Join Type:** LEFT JOIN
- **Join Condition:** PATIENTS.PATIENT_ID = PRESCRIPTIONS.PATIENT_ID
- **Description:** Enriches each patient record with their prescription details. One patient can have multiple prescriptions, resulting in a denormalized view.

### 2. join_with_doctors (Join)
- **Inputs:** PATIENTS_PRESCRIPTIONS_joined, DOCTORS
- **Output:** PATIENT_DOCTOR_RX
- **Join Type:** LEFT JOIN
- **Join Condition:** PATIENTS_PRESCRIPTIONS_joined.DOCTOR_ID = DOCTORS.DOCTOR_ID
- **Description:** Adds doctor specialty and department information to the patient-prescription records.

### 3. group_rx_by_drug (Grouping)
- **Input:** PATIENT_DOCTOR_RX
- **Output:** RX_BY_DRUG_SUMMARY
- **Group By:** DRUG_NAME, SPECIALTY
- **Aggregations:**
  - `PATIENT_ID_distinct` -- Count of distinct patients per drug/specialty
  - `RX_ID_count` -- Total prescriptions per drug/specialty
- **Description:** Summarizes prescription volume by drug and prescribing doctor's specialty.

---

## Output Datasets

### PATIENTS_PRESCRIPTIONS_joined
- **Type:** Filesystem (filesystem_managed)
- **Columns:** 14 (patient demographics + prescription details)

### PATIENT_DOCTOR_RX
- **Type:** Filesystem (filesystem_managed)
- **Columns:** 17 (full denormalized patient-prescription-doctor view)

### RX_BY_DRUG_SUMMARY (Final Output)
- **Type:** Filesystem (filesystem_managed)
- **Columns:**

| Column | Type | Description |
|--------|------|-------------|
| DRUG_NAME | string | Name of the prescribed medication |
| SPECIALTY | string | Medical specialty of prescribing doctor |
| PATIENT_ID_distinct | bigint | Number of unique patients on this drug |
| RX_ID_count | bigint | Total prescriptions for this drug/specialty |

---

## Data Lineage

```
PATIENTS ---------> PATIENTS_PRESCRIPTIONS_joined --> PATIENT_DOCTOR_RX --> RX_BY_DRUG_SUMMARY
PRESCRIPTIONS --/                                /
DOCTORS ----------------------------------------/
```

**Upstream dependencies for RX_BY_DRUG_SUMMARY:**
1. PATIENTS (source) -> via join_patients_prescriptions -> via join_with_doctors -> via group_rx_by_drug
2. PRESCRIPTIONS (source) -> via join_patients_prescriptions -> via join_with_doctors -> via group_rx_by_drug
3. DOCTORS (source) -> via join_with_doctors -> via group_rx_by_drug

---

## Job History (Recent)

| Job ID | Status | Type | Timestamp |
|--------|--------|------|-----------|
| Build_RX_BY_DRUG_SUMMARY__NP__2026-10-03T20-47-48 | DONE | RECURSIVE_FORCED_BUILD | 2026-10-03 20:47 |
| Build_RX_BY_DRUG_SUMMARY__NP__2026-10-03T20-46-03 | FAILED | RECURSIVE_FORCED_BUILD | 2026-10-03 20:46 |
| Build_RX_BY_DRUG_SUMMARY__NP__2026-10-03T20-43-40 | DONE | NON_RECURSIVE_FORCED_BUILD | 2026-10-03 20:43 |
| Build_RX_BY_DRUG_SUMMARY__NP__2026-10-03T20-42-05 | DONE | RECURSIVE_BUILD | 2026-10-03 20:42 |
| Build_RX_BY_DRUG_SUMMARY__NP__2026-10-03T20-39-56 | FAILED | RECURSIVE_BUILD | 2026-10-03 20:39 |
"""

# Create the wiki article
article = wiki.create_article("Flow Documentation", content=ARTICLE_BODY.strip())
print(f"Wiki article created: {article.article_id}")
print("Done!")
